<?php
namespace Modules\Tour\Models;

use App\BaseModel;
use Illuminate\Http\Request;

class TourMeta extends BaseModel
{
    protected $table    = 'bravo_tour_meta';
    protected $fillable = [
        'enable_person_types',
        'person_types',
        'enable_extra_price',
        'extra_price',
        'enable_open_hours',
        'open_hours',
        'discount_by_people',
        'booking_inquiry_type',
        'accept_booking_max_time',
        'robots_meta',
        'booking_form_label',
        'booking_form_url',
        'booking_form_timing',
        'tour_links',
        'tour_mobile_menus',
        'deposit_enable',
        'deposit_amount',
        'deposit_type',
        'deposit_fomular',
        'notes',
        'tour_feature',
        'brochure',
        'adv_banner_image_id',
        'adv_banner_url',
        'review_rating_value',
        'review_best_rating',
        'review_worst_rating',
        'aggregate_rating_value',
        'aggregate_total_review_count',
        'review_author',
        'product_condition',
        'product_url',
        'schema_price',
        'price_valid_date',
        'availability',
        'price_currency'
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'person_types'       => 'array',
        'extra_price'        => 'array',
        'open_hours'         => 'array',
        'discount_by_people' => 'array',
        'robots_meta'       => 'array',
        'tour_links'        => 'array',
        'tour_mobile_menus' => 'array',
        'notes' => 'array',
        'tour_feature' => 'array'
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ( $this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
